### ISSUE TITLE
client.VirtualMachine.ListVirtualMachines fails with can't unmarshal string into int64 error.

### ISSUE THREAD

**Issue by rhugga** [xanzy/go-cloudstack#137] opened 2021-06-09 18:59 UTC
We are using API version 4.14.0.0-16shapeblue3.

I have the following code:
```
lp := client.VirtualMachine.NewListVirtualMachinesParams()
lp.SetListall(true)   
lp.SetPagesize(10)    
lp.SetPage(0)     
virtualMachines, err := client.VirtualMachine.ListVirtualMachines(lp)  
if err != nil {     
    return nil, nil, err     
}
```

I get this error:

```json: cannot unmarshal string into Go struct field VirtualMachine.virtualmachine.ostypeid of type int64"```

Is this a library bug or is there something I'm doing wrong here? I can't seem to increase debugging to see what the object it's complaining about.

**Comment by olivierlemasle** [comment] 2021-07-13 20:06
This is a duplicate of #117 or #131.

It was fixed in v2 (as this is a breaking change in CloudStack, this is also a breaking change in this go client, so the import path has to change).

Import v2 with:

    go get github.com/xanzy/go-cloudstack/v2/cloudstack

**Comment by svanharmelen** [comment] 2021-07-14 09:29
This is indeed fixed in the latest version...

**Closed as completed by svanharmelen** 2021-07-14 09:29 UTC
